//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.19 at 05:34:46 AM IRST 
//


package DAG;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the DAG package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AdagJobArgumentFilename_QNAME = new QName("http://pegasus.isi.edu/schema/DAX", "filename");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: DAG
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Adag }
     * 
     */
    public Adag createAdag() {
        return new Adag();
    }

    /**
     * Create an instance of {@link Adag.Child }
     * 
     */
    public Adag.Child createAdagChild() {
        return new Adag.Child();
    }

    /**
     * Create an instance of {@link Adag.Job }
     * 
     */
    public Adag.Job createAdagJob() {
        return new Adag.Job();
    }

    /**
     * Create an instance of {@link Adag.Filename }
     * 
     */
    public Adag.Filename createAdagFilename() {
        return new Adag.Filename();
    }

    /**
     * Create an instance of {@link StdioType }
     * 
     */
    public StdioType createStdioType() {
        return new StdioType();
    }

    /**
     * Create an instance of {@link FilenameType }
     * 
     */
    public FilenameType createFilenameType() {
        return new FilenameType();
    }

    /**
     * Create an instance of {@link PlainFilenameType }
     * 
     */
    public PlainFilenameType createPlainFilenameType() {
        return new PlainFilenameType();
    }

    /**
     * Create an instance of {@link Adag.Child.Parent }
     * 
     */
    public Adag.Child.Parent createAdagChildParent() {
        return new Adag.Child.Parent();
    }

    /**
     * Create an instance of {@link Adag.Job.Argument }
     * 
     */
    public Adag.Job.Argument createAdagJobArgument() {
        return new Adag.Job.Argument();
    }

    /**
     * Create an instance of {@link Adag.Job.Profile }
     * 
     */
    public Adag.Job.Profile createAdagJobProfile() {
        return new Adag.Job.Profile();
    }

    /**
     * Create an instance of {@link Adag.Job.Stdin }
     * 
     */
    public Adag.Job.Stdin createAdagJobStdin() {
        return new Adag.Job.Stdin();
    }

    /**
     * Create an instance of {@link Adag.Job.Stdout }
     * 
     */
    public Adag.Job.Stdout createAdagJobStdout() {
        return new Adag.Job.Stdout();
    }

    /**
     * Create an instance of {@link Adag.Job.Stderr }
     * 
     */
    public Adag.Job.Stderr createAdagJobStderr() {
        return new Adag.Job.Stderr();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlainFilenameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pegasus.isi.edu/schema/DAX", name = "filename", scope = Adag.Job.Argument.class)
    public JAXBElement<PlainFilenameType> createAdagJobArgumentFilename(PlainFilenameType value) {
        return new JAXBElement<PlainFilenameType>(_AdagJobArgumentFilename_QNAME, PlainFilenameType.class, Adag.Job.Argument.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlainFilenameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pegasus.isi.edu/schema/DAX", name = "filename", scope = Adag.Job.Profile.class)
    public JAXBElement<PlainFilenameType> createAdagJobProfileFilename(PlainFilenameType value) {
        return new JAXBElement<PlainFilenameType>(_AdagJobArgumentFilename_QNAME, PlainFilenameType.class, Adag.Job.Profile.class, value);
    }

}
