//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.19 at 05:34:46 AM IRST 
//


package DAG;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProfileNamespace.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProfileNamespace">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="pegasus"/>
 *     &lt;enumeration value="condor"/>
 *     &lt;enumeration value="dagman"/>
 *     &lt;enumeration value="env"/>
 *     &lt;enumeration value="hints"/>
 *     &lt;enumeration value="globus"/>
 *     &lt;enumeration value="selector"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ProfileNamespace")
@XmlEnum
public enum ProfileNamespace {

    @XmlEnumValue("pegasus")
    PEGASUS("pegasus"),
    @XmlEnumValue("condor")
    CONDOR("condor"),
    @XmlEnumValue("dagman")
    DAGMAN("dagman"),
    @XmlEnumValue("env")
    ENV("env"),
    @XmlEnumValue("hints")
    HINTS("hints"),
    @XmlEnumValue("globus")
    GLOBUS("globus"),
    @XmlEnumValue("selector")
    SELECTOR("selector");
    private final String value;

    ProfileNamespace(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProfileNamespace fromValue(String v) {
        for (ProfileNamespace c: ProfileNamespace.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
